version: '3.9'

networks:
  condornps_default:
    external: true

services:
  streamlit-app:
    image: condor_ecommerce
    container_name: dash_ecommerce
    ports:
      - "16549:16549"
    volumes:
      - .:/app
    networks:
      - condornps_default

